### ISSUE TITLE
describe formats a little better, and add possible formats as command-line help

### ISSUE THREAD

**Issue by hardtopnet** [null511/MC-PBR-Pipeline#3]
There is currently no indication on what the formats are. I had to check the code to find the possible input-output formats.
There should be a help message on the command line that gives the possible formats.

**Comment by null511** [comment]
I'm assuming you mean PBR encoding rather than image encoding? There is a placeholder for that page but it needs to be updated; I'll get some info up today.

If you were referring to image encodings, then yes that's an excellent point. Will also handle this today.

**Comment by hardtopnet** [comment]
I was mentioning PBR formats I haven't been to image formats yet ^^ thanks !

**Comment by null511** [comment]
Updated documentation for release 0.4.0 - I chose not to include further command-line argument descriptions because while you _could_ specify this property at publish time, you would typically use the [Pack.properties](https://github.com/null511/MC-PBR-Pipeline/wiki/Pack-Properties) file to define output format/mappings.

Documentation for [custom PBR formats](https://github.com/null511/MC-PBR-Pipeline/wiki/PBR-Channel-Encoding) and [image formats](https://github.com/null511/MC-PBR-Pipeline/wiki/Image-Formats) have also been updated.
